language: node_js
node_js:
  - '7'
before_script:
  - npm install -g gulp
  - npm run buildfast
  - npm start &
  - sleep 1
script:
  - npm run test-screener
after_success:
  - chmod ugo+x ./deploy.sh
  - ./deploy.sh